CREATE SCHEMA IF NOT EXISTS APP_DB;

CREATE TABLE IF NOT EXISTS STOCKS (
    STOCKID	BIGINT(19)	NOT NULL PRIMARY KEY AUTO_INCREMENT,
    AMOUNT	INTEGER(10)	NOT	NULL,
    AUTHORIZED_CAPITAL	INTEGER(10)	NOT NULL,
    COMMENT	VARCHAR(255),
    DUTY_PAID	DOUBLE(17)	NOT	NULL,
    EDRPOU	INTEGER(10)	NOT	NULL,
    FULL_NOMINAL_COST	DOUBLE(17)	NOT	NULL,
    NOMINAL_COST	DOUBLE(17)	NOT	NULL,
    PRODACTION_DATE	TIMESTAMP(9)   NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    ID	BIGINT(19)	NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CREATED_DATE	TIMESTAMP(9),
    LAST_MODIFIED_DATE	TIMESTAMP(9),
    NAME	VARCHAR(255),
    CREATED_BY_ID	BIGINT(19),
    LAST_MODIFIED_BY_ID	BIGINT(19)
);
